from __future__ import annotations

# Shared schemas, defaults, and validation tolerances.
# Business logic is intentionally unchanged from the retained legacy monolith.

AMOUNT_TOLERANCE = 0.05
FACTOR_TOLERANCE = 1e-8

COUNTER_ROLE_MAP = {
    "CHECK_DOC_NO": ("CHECK", "D"),
    "R2_CHECK_NO": ("R2", "D"),
    "ACRN_CHECK_COUNTER": ("ACRN", "D"),
    "BC_BATCH_NO": ("BC", "D"),
    "R2_LINE_NO": ("R2", "L"),
}

HDR_SCHEMA = ['TableName', 'DOC_NO', 'DOC_TYPE', 'DOC_CATEGORY', 'CHECK_NO', 'DOC_STATUS', 'CHECK_COUNTER', 'CRDT_DOC_NO', 'CRDT_LINE', 'CRDT_DOC_TYPE', 'CRDT_DOC_CATEGORY', 'CRDT_CHECK_NO', 'MANUAL_AUTO', 'AUTO_BATCH', 'STATUS', 'BANK_ID', 'ACCOUNT_NO', 'CHECKBOOK_NO', 'ACCTNO', 'SUBC', 'PAYTO', 'PAYTO_SUBC', 'PAYTO_CCODE', 'CUST_VEND', 'CHECK_DATE', 'PAYMENT_DATE', 'NOTE', 'PAYEE', 'GL_CODE', 'COMPANY', 'DIVISION', 'DEPART', 'LAST_STATEMENT_BALANCE', 'INFO_BANK_ID', 'INFO_BANK_NAME', 'INFO_SWIFT', 'INFO_ACCOUNT_NO', 'INFO_BRANCH_NO', 'WIRE_PROCESS_DATE', 'WIRE_FILE_NAME', 'CC_CREDITCARD', 'CC_NAME', 'CC_NUMBER', 'CC_EXP', 'PRINT_DATE', 'POST_GL_DATE', 'POST_GL', 'BATCH_NO', 'BATCH_DATE', 'STATEMENT_DOC_NO', 'DEPOSIT_DOC_NO', 'CLEARED', 'CLEARED_BY', 'CLEARED_ON', 'CLEARED_CURRENCY_STATE', 'PRINTED_ON', 'CURENCY_STATE', 'CURENCY_BASE', 'CURENCY_CONV', 'CURENCY_FACTOR', 'CURENCY_DATE', 'DISCOUNT', 'DISCOUNT_DISCREPANCY', 'NETAMOUNT', 'NETAMOUNT_DISCREPANCY', 'AMOUNT', 'APPLIED', 'CURRENCY_DISCREPANCY', 'OPEN_BALANCE', 'C_AMOUNT', 'C_DISCOUNT', 'C_DISCOUNT_DISCREPANCY', 'C_NETAMOUNT', 'C_NETAMOUNT_DISCREPANCY', 'C_APPLIED', 'C_CURRENCY_DISCREPANCY', 'C_OPEN_BALANCE', 'ORIG_DISCOUNT', 'ORIG_DISCOUNT_DISCREPANCY', 'ORIG_NETAMOUNT', 'ORIG_NETAMOUNT_DISCREPANCY', 'ORIG_AMOUNT', 'ORIG_APPLIED', 'ORIG_OPEN_BALANCE', 'C_ORIG_AMOUNT', 'C_ORIG_DISCOUNT', 'C_ORIG_DISCOUNT_DISCREPANCY', 'C_ORIG_NETAMOUNT', 'C_ORIG_NETAMOUNT_DISCREPANCY', 'C_ORIG_APPLIED', 'C_ORIG_OPEN_BALANCE', 'PAID_BY_ACH', 'ACH_ACCOUNT_NO', 'ACH_ACCOUNT_NAME', 'ACH_TRANSACTION_CODE', 'ACH_BANK_NAME', 'ACH_ROUTING_NO', 'BRANCH_NO', 'BANK_NO', 'BANK_NAME', 'ACCOUNT_CURRENCY', 'ACCOUNT_AMOUNT', 'ACCOUNT_FACTOR', 'ACCOUNT_FACTOR_DATE', 'TRANSFER_GL_CODE', 'ACCOUNT_ORIG_AMOUNT', 'DOCUMENT_REFERENCE', 'MEMO', 'SIGN_1', 'SIGN_2', 'SIGN_3', 'SIGN_4', 'SIGN_5', 'SIGN_1_APR', 'SIGN_2_APR', 'SIGN_3_APR', 'SIGN_4_APR', 'SIGN_5_APR', 'SIGN_1_DATE', 'SIGN_2_DATE', 'SIGN_3_DATE', 'SIGN_4_DATE', 'SIGN_5_DATE', 'APPLIED_BY', 'ACH_PAYMENT_TYPE', 'RECLOCK', 'ADDED_USR', 'ADDED_DTE', 'UPDATED_USR', 'UPDATED_DTE']
LINE_SCHEMA = ['TableName', 'DOC_NO', 'DOC_TYPE', 'DOC_CATEGORY', 'DOC_STATUS', 'CHECK_NO', 'PAY_USER_DOC', 'PAY_DOC_CATEGORY', 'LINE', 'PAY_DOC_NO', 'PAY_APPLY', 'PAY_DOC_DATE', 'PAY_TYPE', 'DISCOUNT', 'DISCOUNT_DISCREPANCY', 'NETAMOUNT', 'NETAMOUNT_DISCREPANCY', 'AMOUNT', 'CURRENCY_DISCREPANCY', 'ORIG_DISCOUNT', 'ORIG_DISCOUNT_DISCREPANCY', 'ORIG_NETAMOUNT', 'ORIG_NETAMOUNT_DISCREPANCY', 'ORIG_AMOUNT', 'ORIG_CURRENCY_DISCREPANCY', 'ACCTNO', 'SUBC', 'GL_CODE_AMT', 'GL_CODE_DISC', 'GL_CODE_AMT_DISCREPANCY', 'GL_CODE_DISC_DISCREPANCY_DB', 'GL_CODE_DISC_DISCREPANCY_CR', 'COMPANYNO', 'DIVISION', 'DEPART', 'C_DISCOUNT', 'C_DISCOUNT_DISCREPANCY', 'C_NETAMOUNT', 'C_NETAMOUNT_DISCREPANCY', 'C_AMOUNT', 'C_CURRENCY_DISCREPANCY', 'C_ORIG_DISCOUNT', 'C_ORIG_DISCOUNT_DISCREPANCY', 'C_ORIG_NETAMOUNT', 'C_ORIG_NETAMOUNT_DISCREPANCY', 'C_ORIG_AMOUNT', 'C_ORIG_CURRENCY_DISCREPANCY', 'FORM_1099TYPE', 'TRANSACTION_ID', 'TRANSACTION_ID_SOURCE', 'STATEMENT_DOC_NO', 'CLEARED', 'CLEARED_BY', 'CLEARED_ON', 'RECLOCK', 'ADDED_USR', 'ADDED_DTE', 'UPDATED_USR', 'UPDATED_DTE']
ARAP_SCHEMA = ['TableName', 'DOC_NO', 'LINE', 'DOC_CATEGORY', 'USER_DOC', 'DOC_TYPE', 'AR_AP', 'DOC_STATUS', 'PARENT_DOC_NO', 'PARENT_LINE', 'PARENT_DOCCATEGORY', 'ACCTNO', 'SUBC', 'CUST_VEND', 'CURENCY_STATE', 'CURENCY_BASE', 'CURENCY_CONV', 'CURENCY_FACTOR', 'CURENCY_DATE', 'GL_ACCOUNT', 'COMPANYNO', 'DIVISION', 'DEPART', 'DOC_DATE', 'DUE_DATE', 'POSTED_AR_AP', 'PAYTO', 'PAYTO_SUBC', 'TERM_CODE', 'DOC_TOTAL', 'C_DOC_TOTAL', 'PAID_TOTAL', 'C_PAID_TOTAL', 'VOID_TOTAL', 'C_VOID_TOTAL', 'BALANCE_TOTAL', 'C_BALANCE_TOTAL', 'DISCOUNT_AMT', 'C_DISCOUNT_AMT', 'RECLOCK', 'ADDED_USR', 'ADDED_DTE', 'UPDATED_USR', 'UPDATED_DTE']
HDR_DEFAULTS = {'TableName': 'dbo.CHECK_HDR', 'DOC_TYPE': 'AR', 'DOC_CATEGORY': 'R2', 'DOC_STATUS': 1, 'CRDT_LINE': 0, 'MANUAL_AUTO': 'M', 'POST_GL': 'N', 'CLEARED': 'N', 'CLEARED_CURRENCY_STATE': 1, 'CURENCY_STATE': None, 'DISCOUNT_DISCREPANCY': 0, 'NETAMOUNT_DISCREPANCY': 0, 'CURRENCY_DISCREPANCY': 0, 'OPEN_BALANCE': 0, 'C_DISCOUNT_DISCREPANCY': 0, 'C_NETAMOUNT_DISCREPANCY': 0, 'C_CURRENCY_DISCREPANCY': 0, 'C_OPEN_BALANCE': 0, 'ORIG_DISCOUNT': 0, 'ORIG_DISCOUNT_DISCREPANCY': 0, 'ORIG_NETAMOUNT': 0, 'ORIG_NETAMOUNT_DISCREPANCY': 0, 'ORIG_AMOUNT': 0, 'ORIG_APPLIED': 0, 'ORIG_OPEN_BALANCE': 0, 'C_ORIG_AMOUNT': 0, 'C_ORIG_DISCOUNT': 0, 'C_ORIG_DISCOUNT_DISCREPANCY': 0, 'C_ORIG_NETAMOUNT': 0, 'C_ORIG_NETAMOUNT_DISCREPANCY': 0, 'C_ORIG_APPLIED': 0, 'C_ORIG_OPEN_BALANCE': 0, 'PAID_BY_ACH': 'N', 'ACCOUNT_ORIG_AMOUNT': 0, 'SIGN_1': 'N', 'SIGN_2': 'N', 'SIGN_3': 'N', 'SIGN_4': 'N', 'SIGN_5': 'N', 'SIGN_1_APR': 'N', 'SIGN_2_APR': 'N', 'SIGN_3_APR': 'N', 'SIGN_4_APR': 'N', 'SIGN_5_APR': 'N', 'RECLOCK': None}
# CHECK_LINE amount source rule used by generate():
#   Each line resolves its own invoice factor:
#     same-pair 1 -> INV_HDR factor -> ARAP factor -> TBLCONV fallback
#   C_AMOUNT     = INV_HDR.C_DOC_TOTAL
#   C_NETAMOUNT  = input C_PAID_AMOUNT (current receipt delta)
#   NETAMOUNT    = C_NETAMOUNT / line factor
#   C_DISCOUNT   = C_AMOUNT - C_NETAMOUNT
#
# CHECK_HDR factor rules:
#   ACCOUNT_FACTOR is sourced from the TBLCONV base-to-payment lookup;
#   ACCOUNT_AMOUNT / AMOUNT remains a validation relationship.
#   CURENCY_FACTOR uses the common line factor when every line has the
#   same factor. Otherwise it is the effective receipt factor
#   C_AMOUNT / AMOUNT.
#
# ACCOUNT_AR_AP paid totals are cumulative:
#   new C_PAID_TOTAL = existing C_PAID_TOTAL + current C_NETAMOUNT
#   new PAID_TOTAL   = existing PAID_TOTAL + current NETAMOUNT
#
# RMB and CNY are treated as the same currency.
# INV_LINE is not used by this generation path.
LINE_DEFAULTS = {'TableName': 'dbo.CHECK_LINE', 'DOC_TYPE': 'AR', 'DOC_CATEGORY': 'R2', 'DOC_STATUS': None, 'PAY_DOC_CATEGORY': 'IV', 'PAY_TYPE': 'I', 'DISCOUNT_DISCREPANCY': 0, 'NETAMOUNT_DISCREPANCY': 0, 'CURRENCY_DISCREPANCY': 0, 'ORIG_DISCOUNT': 0, 'ORIG_DISCOUNT_DISCREPANCY': 0, 'ORIG_NETAMOUNT': 0, 'ORIG_NETAMOUNT_DISCREPANCY': 0, 'ORIG_AMOUNT': 0, 'ORIG_CURRENCY_DISCREPANCY': 0, 'GL_CODE_AMT_DISCREPANCY': '790550-00', 'GL_CODE_DISC_DISCREPANCY_DB': '790550-00', 'GL_CODE_DISC_DISCREPANCY_CR': '790550-00', 'C_DISCOUNT_DISCREPANCY': 0, 'C_NETAMOUNT_DISCREPANCY': 0, 'C_CURRENCY_DISCREPANCY': 0, 'C_ORIG_DISCOUNT': 0, 'C_ORIG_DISCOUNT_DISCREPANCY': 0, 'C_ORIG_NETAMOUNT': 0, 'C_ORIG_NETAMOUNT_DISCREPANCY': 0, 'C_ORIG_AMOUNT': 0, 'C_ORIG_CURRENCY_DISCREPANCY': 0, 'CLEARED': 'N', 'RECLOCK': None}
